[package]
name = "openlms"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.0", features = ["postgres"] }
dotenvy = "0.15"

[workspace]
members = ["openlms-server"]
default-members = ["openlms-server"]
